# Generated by Django 3.1.4 on 2022-06-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_state'),
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=512, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_wa_number',
            field=models.BooleanField(default=False, verbose_name='Whatsapp Notification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.state', verbose_name='state'),
        ),
    ]
