# Generated by Django 3.1.4 on 2022-06-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_key
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_gst'),
        ('config', '0037_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20220615_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, help_text='row id', unique=True)),
                ('is_active', models.PositiveSmallIntegerField(default=0, verbose_name='active row')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='row status')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('u_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('inv_no', models.CharField(default=utils.generate_key.code_generator, max_length=8)),
                ('customer_address', models.CharField(max_length=512, null=True, verbose_name='address')),
                ('taxable_amount', models.FloatField(default=0)),
                ('cgst', models.FloatField(default=0)),
                ('sgst', models.FloatField(default=0)),
                ('igst', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('customer_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.state', verbose_name='state')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-u_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, help_text='row id', unique=True)),
                ('is_active', models.PositiveSmallIntegerField(default=0, verbose_name='active row')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='row status')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('u_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('taxable_amount', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'ordering': ('-u_on',),
                'abstract': False,
            },
        ),
    ]
