# Generated by Django 3.1.4 on 2023-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230104_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwisereference',
            name='is_paid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userwisereference',
            name='is_subscribed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userwisereference',
            name='paid_on',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userwisereference',
            name='referral_amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userwisereference',
            name='subscription_amount',
            field=models.FloatField(default=None, null=True),
        ),
    ]
