# Generated by Django 3.1.4 on 2023-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230818_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='ip_address',
            field=models.GenericIPAddressField(default='a00f:a000:a000:a000:0000:a000:a000:a000'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_agent',
            field=models.CharField(default='n/a', max_length=512),
        ),
    ]
