# Generated by Django 2.2.4 on 2019-11-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_auto_20191127_1049"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.NullBooleanField(default=False)),
                ("c_on", models.DateTimeField(auto_now_add=True)),
                ("u_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-u_on",),
            },
        ),
        migrations.RenameField(
            model_name="examquestion",
            old_name="name",
            new_name="note",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.Exam",
            ),
            preserve_default=False,
        ),
    ]
