# Generated by Django 2.2.4 on 2019-11-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_auto_20191127_1229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
