# Generated by Django 2.2.4 on 2020-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0004_auto_20191129_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="is_active",
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="exam",
            name="u_on",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="is_active",
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="u_on",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
