# Generated by Django 3.1.4 on 2020-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0005_auto_20200606_1032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
