# Generated by Django 3.1.4 on 2021-02-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0010_tableattribute_code"),
        ("question", "0007_auto_20210213_0418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.tableattribute",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="question.exam",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="note",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="tbl_header",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.tableheader",
            ),
        ),
    ]
