# Generated by Django 3.1.4 on 2021-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0008_auto_20210227_0742"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="chapter",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
