# Generated by Django 3.1.4 on 2021-07-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0028_auto_20210709_1848"),
        ("question", "0009_exam_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="chapter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.chapter",
            ),
        ),
    ]
