# Generated by Django 3.1.4 on 2021-07-13 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0011_examevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExamEvent",
        ),
    ]
