# Generated by Django 3.1.4 on 2022-02-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0034_questioncategory"),
        ("question", "0013_examquestion_amount2"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="question_category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.questioncategory",
            ),
        ),
    ]
