# Generated by Django 3.1.4 on 2022-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0014_exam_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="question_code",
            field=models.CharField(
                blank=True, help_text="question code", max_length=16, null=True
            ),
        ),
    ]
