# Generated by Django 3.1.4 on 2022-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0015_exam_question_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ("question_code",)},
        ),
        migrations.AlterField(
            model_name="exam",
            name="question_code",
            field=models.CharField(
                blank=True,
                help_text="Question order by serial code",
                max_length=16,
                null=True,
            ),
        ),
    ]
