# Generated by Django 3.1.4 on 2022-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20220221_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='ext_jf_lf',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='tr_date',
            field=models.DateField(null=True),
        ),
    ]
