# Generated by Django 3.1.4 on 2023-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20220702_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
    ]
