# Generated by Django 2.2.4 on 2019-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_auto_20191127_0915"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_active", models.NullBooleanField(default=False)),
                ("c_on", models.DateTimeField(auto_now_add=True)),
                ("u_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-u_on",),
            },
        ),
    ]
