# Generated by Django 2.2.4 on 2020-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_tablewiseheaderwithattribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableattribute",
            name="short_name",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
