# Generated by Django 3.1.4 on 2020-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0006_tableattribute_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableattribute",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="tableheader",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="tablename",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="tablewiseheaderwithattribute",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
