# Generated by Django 3.1.4 on 2021-02-13 04:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0007_auto_20201219_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableattribute",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, help_text="row id", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tableheader",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, help_text="row id", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tablename",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, help_text="row id", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tablewiseheaderwithattribute",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, help_text="row id", unique=True
            ),
        ),
    ]
