# Generated by Django 3.1.4 on 2021-02-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0008_auto_20210213_0418"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablewiseheaderwithattribute",
            name="arithmetic",
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="tablewiseheaderwithattribute",
            name="info",
            field=models.CharField(max_length=512, null=True, verbose_name="help"),
        ),
        migrations.AddField(
            model_name="tablewiseheaderwithattribute",
            name="pair_attr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.tablewiseheaderwithattribute",
            ),
        ),
    ]
