# Generated by Django 3.1.4 on 2021-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0009_auto_20210223_0120"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableattribute",
            name="code",
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
