# Generated by Django 3.1.4 on 2021-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0011_finalruleenginecsv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableattribute",
            name="code",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
