# Generated by Django 3.1.4 on 2021-04-11 09:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0014_auto_20210410_1540"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleEngine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                (
                    "relationship",
                    models.PositiveSmallIntegerField(
                        default=11, verbose_name="relationship"
                    ),
                ),
                (
                    "operation1",
                    models.PositiveSmallIntegerField(
                        default=0, null=True, verbose_name="arithmetic1"
                    ),
                ),
                (
                    "help1",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="information1"
                    ),
                ),
                (
                    "operation2",
                    models.PositiveSmallIntegerField(
                        default=0, null=True, verbose_name="arithmetic2"
                    ),
                ),
                (
                    "help2",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="information2"
                    ),
                ),
                (
                    "header1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="header1",
                        to="config.tableheader",
                        verbose_name="Header1 / Column1 Name",
                    ),
                ),
                (
                    "header2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="header2",
                        to="config.tableheader",
                        verbose_name="Header2 / Column2 Name",
                    ),
                ),
                (
                    "pair_attr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pair_attr",
                        to="config.tableattribute",
                        verbose_name="paired field name",
                    ),
                ),
                (
                    "tbl1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tbl1",
                        to="config.tablename",
                        verbose_name="Table1 Name",
                    ),
                ),
                (
                    "tbl2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tbl2",
                        to="config.tablename",
                        verbose_name="Table2 Name",
                    ),
                ),
                (
                    "tbl_attribute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="config.tableattribute",
                        verbose_name="field name",
                    ),
                ),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="TableWiseHeaderWithAttribute",
        ),
    ]
