# Generated by Django 3.1.4 on 2021-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0016_ruleengine_pair_attr_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleEngine1",
            fields=[
                (
                    "attribute_code",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "atribute_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "pair_with_attribute",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("pairing_priority", models.IntegerField(blank=True, null=True)),
                (
                    "operation1",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "table1_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "header1_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "table1_header1_help",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "operation2",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "table2_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "header2_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "table2_header2_help",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("help1", models.CharField(blank=True, max_length=1024, null=True)),
                ("help2", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "header1_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "header2_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "pair_attr_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("tbl1_id", models.CharField(blank=True, max_length=1024, null=True)),
                ("tbl2_id", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "tbl_attribute_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "pair_attr_priority",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
            options={
                "db_table": "rule_engine1",
                "managed": False,
            },
        ),
    ]
