# Generated by Django 3.1.4 on 2021-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0017_ruleengine1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleengine",
            name="pair_attr_priority",
            field=models.PositiveSmallIntegerField(
                default=None, null=True, verbose_name="order by pair attribute"
            ),
        ),
    ]
