# Generated by Django 3.1.4 on 2021-04-11 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0018_auto_20210411_1906"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RuleEngine1",
        ),
    ]
