# Generated by Django 3.1.4 on 2021-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0019_delete_ruleengine1"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleengine",
            name="status",
            field=models.PositiveIntegerField(default=0, verbose_name="row status"),
        ),
        migrations.AddField(
            model_name="tableattribute",
            name="status",
            field=models.PositiveIntegerField(default=0, verbose_name="row status"),
        ),
        migrations.AddField(
            model_name="tableattribute",
            name="tr_type",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="tableattribute",
            name="c_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created on"),
        ),
        migrations.AlterField(
            model_name="tableattribute",
            name="is_active",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="active row"
            ),
        ),
        migrations.AlterField(
            model_name="tableattribute",
            name="u_on",
            field=models.DateTimeField(auto_now=True, verbose_name="updated on"),
        ),
    ]
