# Generated by Django 3.1.4 on 2021-05-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0022_auto_20210430_0457"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleengine",
            name="tbl_attribute_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.tableheader",
                verbose_name="field type",
            ),
        ),
    ]
