# Generated by Django 3.1.4 on 2021-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0024_auto_20210522_0607"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableheader",
            name="code",
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name="tablename",
            name="code",
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name="ruleengine",
            name="operation1",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "add"), (3, "sub")],
                default=0,
                null=True,
                verbose_name="arithmetic1",
            ),
        ),
        migrations.AlterField(
            model_name="ruleengine",
            name="operation2",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "add"), (3, "sub")],
                default=0,
                null=True,
                verbose_name="arithmetic2",
            ),
        ),
    ]
