# Generated by Django 3.1.4 on 2021-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0027_ruleengine_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleengine",
            name="relationship",
            field=models.PositiveSmallIntegerField(
                choices=[(11, "1 TO 1"), (121, "1 TO MANY")],
                default=11,
                verbose_name="relationship",
            ),
        ),
    ]
