# Generated by Django 3.1.4 on 2021-07-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0028_auto_20210709_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleengine",
            name="header3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="header3",
                to="config.tableheader",
                verbose_name="Header3 / Column3 Name",
            ),
        ),
        migrations.AddField(
            model_name="ruleengine",
            name="help3",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="information3"
            ),
        ),
        migrations.AddField(
            model_name="ruleengine",
            name="operation3",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "add"), (3, "sub")],
                default=0,
                null=True,
                verbose_name="arithmetic3",
            ),
        ),
        migrations.AddField(
            model_name="ruleengine",
            name="tbl3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tbl3",
                to="config.tablename",
                verbose_name="Table3 Name",
            ),
        ),
        migrations.AlterField(
            model_name="ruleengine",
            name="relationship",
            field=models.PositiveSmallIntegerField(
                choices=[(11, "1 TO 1"), (121, "1 TO 2"), (123, "1 TO 3")],
                default=11,
                verbose_name="relationship",
            ),
        ),
    ]
