# Generated by Django 3.1.13 on 2021-09-20 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0030_auto_20210713_1103"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinalRuleEngineCsv",
        ),
    ]
