# Generated by Django 3.1.13 on 2021-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0031_delete_finalruleenginecsv"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleengine",
            name="amount1",
            field=models.PositiveSmallIntegerField(
                default=0, null=True, verbose_name="amount pair with from question"
            ),
        ),
        migrations.AddField(
            model_name="ruleengine",
            name="amount2",
            field=models.PositiveSmallIntegerField(
                default=0, null=True, verbose_name="amount pair with from question"
            ),
        ),
        migrations.AddField(
            model_name="ruleengine",
            name="amount3",
            field=models.PositiveSmallIntegerField(
                default=0, null=True, verbose_name="amount pair with from question"
            ),
        ),
    ]
