# Generated by Django 3.1.4 on 2022-02-18 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0032_auto_20210920_0618"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleengine",
            name="amount1",
            field=models.PositiveSmallIntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(9),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="amount1 pair position from question",
            ),
        ),
        migrations.AlterField(
            model_name="ruleengine",
            name="amount2",
            field=models.PositiveSmallIntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(9),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="amount2 pair position from question",
            ),
        ),
        migrations.AlterField(
            model_name="ruleengine",
            name="amount3",
            field=models.PositiveSmallIntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(9),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="amount3 pair position from question",
            ),
        ),
    ]
