# Generated by Django 3.1.4 on 2022-05-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0034_questioncategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questioncategory",
            options={"ordering": ("order_of",)},
        ),
    ]
