# Generated by Django 3.1.4 on 2022-06-15 05:26

from django.db import migrations, models
import utils.generate_key
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_auto_20220531_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, help_text='row id', unique=True)),
                ('is_active', models.PositiveSmallIntegerField(default=0, verbose_name='active row')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='row status')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('u_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('code', models.CharField(default=utils.generate_key.code_generator, max_length=8)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-u_on',),
                'abstract': False,
            },
        ),
    ]
