# Generated by Django 3.1.4 on 2022-07-01 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleengine',
            name='amount4',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)], verbose_name='amount4 pair position from question'),
        ),
        migrations.AddField(
            model_name='ruleengine',
            name='header4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header4', to='config.tableheader', verbose_name='Header4 / Column4 Name'),
        ),
        migrations.AddField(
            model_name='ruleengine',
            name='help4',
            field=models.CharField(blank=True, max_length=1024, verbose_name='information4'),
        ),
        migrations.AddField(
            model_name='ruleengine',
            name='operation4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'add'), (3, 'sub')], default=0, null=True, verbose_name='arithmetic4'),
        ),
        migrations.AddField(
            model_name='ruleengine',
            name='tbl4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tbl4', to='config.tablename', verbose_name='Table4 Name'),
        ),
    ]
