# Generated by Django 3.1.4 on 2022-07-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20220701_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleengine',
            name='relationship',
            field=models.PositiveSmallIntegerField(choices=[(11, '1 TO 1'), (121, '1 TO 2'), (131, '1 TO 3'), (141, '1 TO 4')], default=11, verbose_name='relationship'),
        ),
    ]
