# Generated by Django 3.1.4 on 2022-07-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_auto_20220702_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableattribute',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
