# Generated by Django 2.2.4 on 2019-11-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0004_tablename"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.FloatField(default=0)),
                ("c_on", models.DateTimeField(auto_now_add=True)),
                ("u_on", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.TableAttribute",
                    ),
                ),
                (
                    "tbl_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.TableHeader",
                    ),
                ),
                (
                    "tbl_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.TableName",
                    ),
                ),
            ],
            options={
                "ordering": ("-u_on",),
            },
        ),
    ]
