# Generated by Django 2.2.4 on 2019-11-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="question.ExamQuestion"
            ),
        ),
    ]
