# Generated by Django 2.2.4 on 2019-11-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_auto_20191127_1229"),
        ("answer", "0002_auto_20191127_1229"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examanswer",
            old_name="name",
            new_name="note",
        ),
        migrations.AddField(
            model_name="examanswer",
            name="exam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.Exam",
            ),
            preserve_default=False,
        ),
    ]
