# Generated by Django 2.2.4 on 2019-12-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_auto_20191129_1051"),
        ("answer", "0003_auto_20191127_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="qun",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.ExamQuestion",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.TableAttribute"
            ),
        ),
    ]
