# Generated by Django 3.1.4 on 2021-07-24 10:51

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0030_auto_20210713_1103"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question", "0012_delete_examevent"),
        ("answer", "0007_answerevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="is_active",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="active row"
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="status",
            field=models.PositiveIntegerField(default=0, verbose_name="row status"),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="c_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created on"),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, help_text="row id", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="u_on",
            field=models.DateTimeField(auto_now=True, verbose_name="updated on"),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("user", "qun", "tbl_name", "tbl_header", "attribute")},
        ),
    ]
