# Generated by Django 3.1.4 on 2021-08-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0030_auto_20210713_1103"),
        ("answer", "0008_auto_20210724_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="operation",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "add"), (3, "sub")],
                default=0,
                null=True,
                verbose_name="arithmetic",
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.ruleengine",
            ),
        ),
    ]
