# Generated by Django 3.1.4 on 2021-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("answer", "0009_auto_20210801_0308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerevent",
            name="action",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
