# Generated by Django 3.1.4 on 2022-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answer", "0010_auto_20210801_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerevent",
            name="answer_by",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="answerevent",
            name="hint",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="answerevent",
            name="user_answer",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
