# Generated by Django 3.1.4 on 2022-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answer", "0011_auto_20220422_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerevent",
            name="archive",
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="answerevent",
            name="score",
            field=models.FloatField(default=0, editable=False),
        ),
    ]
