# Generated by Django 3.1.4 on 2022-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0012_auto_20220516_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerevent',
            name='score',
            field=models.FloatField(db_index=True, default=0, editable=False),
        ),
    ]
