# Generated by Django 3.1.4 on 2022-05-31 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("config", "0036_auto_20220531_1700"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgNotify",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(default=0, verbose_name="row status"),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("response", models.JSONField(null=True)),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(default=0, verbose_name="row status"),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "total_cost",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(default=0, verbose_name="row status"),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=32)),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("days", models.PositiveIntegerField(default=0)),
                (
                    "reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="amount of reward",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="config.course",
                    ),
                ),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(default=0, verbose_name="row status"),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
    ]
