# Generated by Django 3.1.4 on 2022-06-08 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgReturn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="row id",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="active row"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(default=0, verbose_name="row status"),
                ),
                (
                    "c_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "u_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                ("order_id", models.UUIDField()),
                ("token", models.CharField(max_length=255)),
                ("response", models.TextField(null=True)),
                ("request_obj", models.TextField(null=True)),
            ],
            options={
                "ordering": ("-u_on",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pgnotify",
            name="order_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="pgnotify",
            name="request_obj",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="pgnotify",
            name="response",
            field=models.TextField(null=True),
        ),
    ]
