# Generated by Django 3.1.4 on 2022-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20220608_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgnotify",
            name="pg_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
