# Generated by Django 3.1.4 on 2022-06-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_pgnotify_pg_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-days", "code")},
        ),
    ]
