# Generated by Django 3.1.4 on 2022-08-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_auto_20220709_0221'),
        ('shop', '0005_product_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.chapter'),
        ),
    ]
