# Generated by Django 3.1.4 on 2023-08-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productwisechapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
